const CountryCurrencies = [
  {
    country: "Algeria",
    country_iso: "DZ",
    currency: "Algerian Dinar",
    currency_iso: "DZD",
  },
  {
    country: "Angola",
    country_iso: "AO",
    currency: "Angolan Kwanza",
    currency_iso: "AOA",
  },
  {
    country: "Benin",
    country_iso: "BJ",
    currency: "West African CFA Franc",
    currency_iso: "XOF",
  },
  {
    country: "Botswana",
    country_iso: "BW",
    currency: "Botswana Pula",
    currency_iso: "BWP",
  },
  {
    country: "Burkina Faso",
    country_iso: "BF",
    currency: "West African CFA Franc",
    currency_iso: "XOF",
  },
  {
    country: "Burundi",
    country_iso: "BI",
    currency: "Burundian Franc",
    currency_iso: "BIF",
  },
  {
    country: "Cabo Verde",
    country_iso: "CV",
    currency: "Cape Verdean Escudo",
    currency_iso: "CVE",
  },
  {
    country: "Cameroon",
    country_iso: "CM",
    currency: "Central African CFA Franc",
    currency_iso: "XAF",
  },
  {
    country: "Central African Republic",
    country_iso: "CF",
    currency: "Central African CFA Franc",
    currency_iso: "XAF",
  },
  {
    country: "Chad",
    country_iso: "TD",
    currency: "Central African CFA Franc",
    currency_iso: "XAF",
  },
  {
    country: "Comoros",
    country_iso: "KM",
    currency: "Comorian Franc",
    currency_iso: "KMF",
  },
  {
    country: "Congo (Brazzaville)",
    country_iso: "CG",
    currency: "Central African CFA Franc",
    currency_iso: "XAF",
  },
  {
    country: "Congo (Kinshasa)",
    country_iso: "CD",
    currency: "Congolese Franc",
    currency_iso: "CDF",
  },
  {
    country: "Djibouti",
    country_iso: "DJ",
    currency: "Djiboutian Franc",
    currency_iso: "DJF",
  },
  {
    country: "Egypt",
    country_iso: "EG",
    currency: "Egyptian Pound",
    currency_iso: "EGP",
  },
  {
    country: "Equatorial Guinea",
    country_iso: "GQ",
    currency: "Central African CFA Franc",
    currency_iso: "XAF",
  },
  {
    country: "Eritrea",
    country_iso: "ER",
    currency: "Eritrean Nakfa",
    currency_iso: "ERN",
  },
  {
    country: "Eswatini",
    country_iso: "SZ",
    currency: "Swazi Lilangeni",
    currency_iso: "SZL",
  },
  {
    country: "Ethiopia",
    country_iso: "ET",
    currency: "Ethiopian Birr",
    currency_iso: "ETB",
  },
  {
    country: "Gabon",
    country_iso: "GA",
    currency: "Central African CFA Franc",
    currency_iso: "XAF",
  },
  {
    country: "Gambia",
    country_iso: "GM",
    currency: "Gambian Dalasi",
    currency_iso: "GMD",
  },
  {
    country: "Ghana",
    country_iso: "GH",
    currency: "Ghanaian Cedi",
    currency_iso: "GHS",
  },
  {
    country: "Guinea",
    country_iso: "GN",
    currency: "Guinean Franc",
    currency_iso: "GNF",
  },
  {
    country: "Guinea-Bissau",
    country_iso: "GW",
    currency: "West African CFA Franc",
    currency_iso: "XOF",
  },
  {
    country: "Ivory Coast",
    country_iso: "CI",
    currency: "West African CFA Franc",
    currency_iso: "XOF",
  },
  {
    country: "Kenya",
    country_iso: "KE",
    currency: "Kenyan Shilling",
    currency_iso: "KES",
  },
  {
    country: "Lesotho",
    country_iso: "LS",
    currency: "Lesotho Loti",
    currency_iso: "LSL",
  },
  {
    country: "Liberia",
    country_iso: "LR",
    currency: "Liberian Dollar",
    currency_iso: "LRD",
  },
  {
    country: "Libya",
    country_iso: "LY",
    currency: "Libyan Dinar",
    currency_iso: "LYD",
  },
  {
    country: "Madagascar",
    country_iso: "MG",
    currency: "Malagasy Ariary",
    currency_iso: "MGA",
  },
  {
    country: "Malawi",
    country_iso: "MW",
    currency: "Malawian Kwacha",
    currency_iso: "MWK",
  },
  {
    country: "Mali",
    country_iso: "ML",
    currency: "West African CFA Franc",
    currency_iso: "XOF",
  },
  {
    country: "Mauritania",
    country_iso: "MR",
    currency: "Mauritanian Ouguiya",
    currency_iso: "MRU",
  },
  {
    country: "Mauritius",
    country_iso: "MU",
    currency: "Mauritian Rupee",
    currency_iso: "MUR",
  },
  {
    country: "Morocco",
    country_iso: "MA",
    currency: "Moroccan Dirham",
    currency_iso: "MAD",
  },
  {
    country: "Mozambique",
    country_iso: "MZ",
    currency: "Mozambican Metical",
    currency_iso: "MZN",
  },
  {
    country: "Namibia",
    country_iso: "NA",
    currency: "Namibian Dollar",
    currency_iso: "NAD",
  },
  {
    country: "Niger",
    country_iso: "NE",
    currency: "West African CFA Franc",
    currency_iso: "XOF",
  },
  {
    country: "Nigeria",
    country_iso: "NG",
    currency: "Nigerian Naira",
    currency_iso: "NGN",
  },
  {
    country: "Rwanda",
    country_iso: "RW",
    currency: "Rwandan Franc",
    currency_iso: "RWF",
  },
  {
    country: "São Tomé and Príncipe",
    country_iso: "ST",
    currency: "São Tomé and Príncipe Dobra",
    currency_iso: "STN",
  },
  {
    country: "Senegal",
    country_iso: "SN",
    currency: "West African CFA Franc",
    currency_iso: "XOF",
  },
  {
    country: "Seychelles",
    country_iso: "SC",
    currency: "Seychellois Rupee",
    currency_iso: "SCR",
  },
  {
    country: "Sierra Leone",
    country_iso: "SL",
    currency: "Sierra Leonean Leone",
    currency_iso: "SLL",
  },
  {
    country: "Somalia",
    country_iso: "SO",
    currency: "Somali Shilling",
    currency_iso: "SOS",
  },
  {
    country: "South Africa",
    country_iso: "ZA",
    currency: "South African Rand",
    currency_iso: "ZAR",
  },
  {
    country: "South Sudan",
    country_iso: "SS",
    currency: "South Sudanese Pound",
    currency_iso: "SSP",
  },
  {
    country: "Sudan",
    country_iso: "SD",
    currency: "Sudanese Pound",
    currency_iso: "SDG",
  },
  {
    country: "Tanzania",
    country_iso: "TZ",
    currency: "Tanzanian Shilling",
    currency_iso: "TZS",
  },
  {
    country: "Togo",
    country_iso: "TG",
    currency: "West African CFA Franc",
    currency_iso: "XOF",
  },
  {
    country: "Tunisia",
    country_iso: "TN",
    currency: "Tunisian Dinar",
    currency_iso: "TND",
  },
  {
    country: "Uganda",
    country_iso: "UG",
    currency: "Ugandan Shilling",
    currency_iso: "UGX",
  },
  {
    country: "Zambia",
    country_iso: "ZM",
    currency: "Zambian Kwacha",
    currency_iso: "ZMW",
  },
  {
    country: "Zimbabwe",
    country_iso: "ZW",
    currency: "Zimbabwean Dollar",
    currency_iso: "ZWL",
  },
];

export default CountryCurrencies;

const data = {
  data: {
    user: {
      id: "11111111-1111-1111-1111-111111111111",
      aud: "authenticated",
      role: "authenticated",
      email: "example@email.com",
      email_confirmed_at: "2024-01-01T00:00:00Z",
      phone: "",
      last_sign_in_at: "2024-01-01T00:00:00Z",
      app_metadata: {
        provider: "email",
        providers: ["email"],
      },
      user_metadata: {},
      identities: [
        {
          identity_id: "22222222-2222-2222-2222-222222222222",
          id: "11111111-1111-1111-1111-111111111111",
          user_id: "11111111-1111-1111-1111-111111111111",
          identity_data: {
            email: "example@email.com",
            email_verified: false,
            phone_verified: false,
            sub: "11111111-1111-1111-1111-111111111111",
          },
          provider: "email",
          last_sign_in_at: "2024-01-01T00:00:00Z",
          created_at: "2024-01-01T00:00:00Z",
          updated_at: "2024-01-01T00:00:00Z",
          email: "example@email.com",
        },
      ],
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    session: {
      access_token: "<ACCESS_TOKEN>",
      token_type: "bearer",
      expires_in: 3600,
      expires_at: 1700000000,
      refresh_token: "<REFRESH_TOKEN>",
      user: {
        id: "11111111-1111-1111-1111-111111111111",
        aud: "authenticated",
        role: "authenticated",
        email: "example@email.com",
        email_confirmed_at: "2024-01-01T00:00:00Z",
        phone: "",
        last_sign_in_at: "2024-01-01T00:00:00Z",
        app_metadata: {
          provider: "email",
          providers: ["email"],
        },
        user_metadata: {},
        identities: [
          {
            identity_id: "22222222-2222-2222-2222-222222222222",
            id: "11111111-1111-1111-1111-111111111111",
            user_id: "11111111-1111-1111-1111-111111111111",
            identity_data: {
              email: "example@email.com",
              email_verified: false,
              phone_verified: false,
              sub: "11111111-1111-1111-1111-111111111111",
            },
            provider: "email",
            last_sign_in_at: "2024-01-01T00:00:00Z",
            created_at: "2024-01-01T00:00:00Z",
            updated_at: "2024-01-01T00:00:00Z",
            email: "example@email.com",
          },
        ],
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
    },
  },
  error: null,
};
